events {
    worker_connections 1024;
}

http {
    upstream aspnetcore {
        server starter-app-dev:8080;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/aspnetapp.crt;
        ssl_certificate_key /etc/nginx/certs/aspnetapp.key;

        location / {
            proxy_pass http://aspnetcore;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
